language: elixir
elixir: '1.8'
otp_release: '21.2'

env:
  - VAULT_VERSION=1.0.2

before_script: .ci/fetch-vault.sh

jobs:
  include:
    - script:
        # This is basically `mix test` with coverage enabled.
        - VAULT_PATH=$(pwd) mix coveralls.json
        - mix format --check-formatted
        # This will mention FIXME and TODO comments without failing, any other
        # issue fails the build.
        - mix credo
        - mix inch.report
      after_success: bash <(curl -s https://codecov.io/bash)

    # Skip Elixir 1.7 while we don't have many parallel builds
    - elixir: '1.7'
      # Only run tests. We do the other checks in the primary build.
      script: VAULT_PATH=$(pwd) mix test

    - elixir: '1.6'
      otp_release: '20.3'
      # Only run tests. We do the other checks in the primary build.
      script: VAULT_PATH=$(pwd) mix test

    - name: "dialyzer"
      cache:
        directories:
          - $HOME/.mix
          - $HOME/.pltcache
      before_script: travis_wait .ci/build-plt-cache.sh
      script: mix dialyzer --halt-exit-status

    - stage: release
      if: tag IS present

      env:
        # HEX_API_KEY=[secret]
        - secure: "hIsgbCOKX4xMJbQuZZfuNU8GhuS5lSMK9rADLpTDnuhZhVYmdXz2YcgTWkbmcQgiJW48IaNrsMlsr3kq6Z5NGj0mjiK0zwqVqHiaC8impBYRdSlJSkG/oZa1tjc/fpO3TZ3Gz+KyY7Zc1VoQNGSPYCr6fvEAgRHL+DvWdaMzoq6poHoQfE4maGvD4sKa6d9hpf1dE2gRvQy4SMCp352/TpauxLIDF/3ZZBASf8HkTSrJqvyWDqPAE7rkxnn4MJltXQgiv38DWZlh8qNOhptjfje/D89EqlO0qyZRWAVPFVU5mV+2x4drusfqcvfWl5iSWwzgUAuKGkWuYn665IMzL4nuVx5YvqJFPgs9Gl+FRCliZOJFzPUm0EBUHoAVSQcvEQm0HM31Sl12VPlSD8Uhy2uhrFjgP08hdYQ0rMUNZfXYB4YLY+lsplN4Pkn3SVZorLgHVXMAINKzUIq6rPq1sY7QjgpoD78NxZ4nh+rSg8EhA1Y8XS6MMW7yU2uC1kJE4wyCFd//YcSmcROTzbwlBJ9oqCbmp2Jv5bsiDW/AZlX2mr/EUyuCIta356CiZ6B7o0KNs+CiXKVLNpZqTixqAuhI/0RMxfW+aT9r9b3V7qXf/cLiDvD2PlPWAYeURWgbpC/Qm9polJ5JZvXVJAY0elu4Q18Anayq/G0KPBTTMsU="
      deploy:
        provider: script
        script: mix hex.publish --yes
        on: {tags: true}
        skip_cleanup: true  # Don't clean up deps

      script: skip
      before_script: skip
