language: elixir
elixir: '1.8'
otp_release: '21.2'

env:
  - VAULT_VERSION=1.0.2

before_script: .ci/fetch-vault.sh

jobs:
  include:
    - script:
        # This is basically `mix test` with coverage enabled.
        - VAULT_PATH=$(pwd) mix coveralls.json --umbrella
        - mix format --check-formatted
        # This will mention FIXME and TODO comments without failing, any other
        # issue fails the build.
        - mix credo
        - mix inch.report
      after_success: bash <(curl -s https://codecov.io/bash)

    # Skip Elixir 1.7 while we don't have many parallel builds
    - elixir: '1.7'
      # Only run tests. We do the other checks in the primary build.
      script: VAULT_PATH=$(pwd) mix test

    - elixir: '1.6'
      otp_release: '20.3'
      # Only run tests. We do the other checks in the primary build.
      script: VAULT_PATH=$(pwd) mix test

    - name: "dialyzer"
      cache:
        directories:
          - $HOME/.mix
          - $HOME/.pltcache
      before_script: travis_wait .ci/build-plt-cache.sh
      script: mix dialyzer --halt-exit-status

    - stage: release
      if: tag IS present

      env:
        # HEX_API_KEY=<secret>
        - secure: "dFLvTUZBPYekf0mpnx7yo/hKLgiOBuvZPMdsHjj6Z6CxhA7Hwskyab0ZfA2MMdo0GnmX5+i4dz691RcHiIMN6kPXkyXdM0WGC0JXqr6eSdQK6m/vgupYt+bkhdXY9UhSzcMXMOid2S2rNEXooMxnMl5B0EfvVTyyGcGuHcuYneG8KwiAimsESx/NGYDrhLvXO5iJy+dBTHdTBma5ucNQ33c9mGfVkjgKosZtr6LbS97fWS/TZFedn8KcKfxt2eqsuUPVbfa+ayfTKFiC+AovFOoRlOmSC60NVJy9CTzjVEpSM/jsLQExgcV9ajHguSXfUiNXxgilXHyFo/iHiD/WMmp0iBFiF90yNmcYbcOynmSEZXJplqP800R+rt3/+ZC7vJbuGqTKtVD2b1s12GfaJxVuYsnqyeE0h4EeHUawRxVqt4vUDvZ4+2CgC97myYsg6vuxPXL1IeJQ5Hn9SJ5V5uQvMIkPaDV3hUP+u5cg4ps6wNoPOvlZbn2f+bY0KkSS/5Dng9uT1Ru9C1k5FaTDe68TpoNBHvY29k/2qpPjgwAMK3GZ+LB8J8fzHOPJbQG1lHdDHifr+TwsHTJ9Toq6st1V0mVUgwbF6OdPc7jxxJ7rne5skjLCm+KJoE6UxDRINUVTuajJi6aEgHOwiaiOhJ8m/q6RUeXTYPReeqXl+mA="
      deploy:
        - provider: script
          script: cd apps/exvault && mix hex.publish --yes
          on: {tags: true}
        - provider: script
          script: cd apps/vaultdevserver && mix hex.publish --yes
          on: {tags: true}

      script: skip

# We already have PR builds, so don't build PR branches as well.
branches:
  only:
    - master
